### ISSUE TITLE
best cheat but...

### ISSUE THREAD

**Issue by TheCheaterFromEstonia** [kadeeq/ProjectX#114]
bhop does not work

**Comment by Unk0wn1337** [comment]
write yourself dude

**Comment by SourLen** [comment]
Can you give any further info on the issue, maybe an error message or smth?

**Comment by Unk0wn1337** [comment]
@XanOpiat  do you think this guy have enough programming skills to debug and figure out what the problem might be? 😂

**Comment by TheCheaterFromEstonia** [comment]
> @XanOpiat do you think this guy have enough programming skills to debug and figure out what the problem might be? 😂

do you think that you can touch some grass and get bitches?😂
