### ISSUE TITLE
.

### ISSUE THREAD

**Issue by LhymeFruit** [kadeeq/ProjectX#128]

**Comment by SourLen** [comment]
Try restarting, should probably fix the issue

**Comment by LhymeFruit** [comment]
tried that it doesnt change anything

> Try restarting, should probably fix the issue

**Comment by SourLen** [comment]
alright i am looking into it

**Comment by wrzxw** [comment]
about this error:
`File "/home/deck/Downloads/Python-CSGO-Cheat-main/Utils/Offsets.py", line 74, in`
`pm1 = pymem.Pymem("csgo.exe")`

try installing Pymem by typing in the terminal:
`pip install Pymem`

then import pymem by adding this with the other imported modules:
`import pymem` or `import Pymem`

also if that doesnt work, pls stop using new versions and use the one the owner uses for less errors :)

**Comment by SourLen** [comment]
just out of curiosity why do you think hes using a newer version than me?

**Comment by wrzxw** [comment]
i mean, maybe?
